[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "robotic_researcher"
version = "1.0.0"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]
